### ISSUE TITLE
Compilation error on MSVC 16.4.4

### ISSUE THREAD

**Issue by septag** [seleznevae/ceraii#2]
Trying to build on MSVC 16.4.4, but encounter several warnings and errors:

```
cmake -LH
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Code/Temp/ceraii/build
-- Cache values
// Build for coveralls
CERAII_COVERALLS_BUILD:BOOL=OFF

// Doing actions before evaluating return expression
CERAII_DO_BEFORE_EXIT:BOOL=ON

// Build with gcc
CERAII_GCC_BUILD:BOOL=OFF

// Build with msvc
CERAII_MSVC_BUILD:BOOL=ON

// Build with turned on optimizations
CERAII_PERF_OPTIMIZED_BUILD:BOOL=OFF

// Test build with sanitizers and small library stack size
CERAII_TEST_BUILD:BOOL=ON
```

ceraii.c compilation:
```
1>cl /c /ID:\Code\Temp\ceraii\src /Zi /Wall /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D CERAII_CONF_ENV_STACK_SIZE=2 /D CERAII_CONF_ALLOC_ENV_STACK_INITIAL_CAPACITY=10 /D CERAII_ACTIONS_BEFORE_RETURN_EXPRESSION /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"example.dir\Debug\\" /Fd"example.dir\Debug\vc142.pdb" /Gd /TC /errorReport:prompt  -O0 -fsanitize=address D:\Code\Temp\ceraii\src\ceraii.c
1>cl : command line warning D9002: ignoring unknown option '-O0'
1>cl : command line warning D9002: ignoring unknown option '-fsanitize=address'
1>ceraii.c
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vcruntime.h(265,9): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vcruntime.h(268,11): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt.h(212,7): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\malloc.h(45,1): warning C4820: '_heapinfo': '4' bytes padding added after data member '_useflag'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\smmintrin.h(82,5): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\nmmintrin.h(35,5): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\wmmintrin.h(34,5): warning C4668: '__cplusplus' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\immintrin.h(1346,50): warning C4255: '_readfsbase_u32': no function prototype given: converting '()' to '(void)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\immintrin.h(1347,50): warning C4255: '_readgsbase_u32': no function prototype given: converting '()' to '(void)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\immintrin.h(1348,50): warning C4255: '_readfsbase_u64': no function prototype given: converting '()' to '(void)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\immintrin.h(1349,50): warning C4255: '_readgsbase_u64': no function prototype given: converting '()' to '(void)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\ammintrin.h(251,17): warning C4255: '__slwpcb': no function prototype given: converting '()' to '(void)'
1>D:\Code\Temp\ceraii\src\ceraii.h(88,17): warning C4324: 'stack_return_item': structure was padded due to alignment specifier
1>D:\Code\Temp\ceraii\src\ceraii.h(88,17): warning C4820: 'stack_return_item': '12' bytes padding added after data member 'index_'
1>D:\Code\Temp\ceraii\src\ceraii.c(151,38): error C2036: 'void *': unknown size
1>D:\Code\Temp\ceraii\src\ceraii.c(164,56): error C2036: 'void *': unknown size
1>D:\Code\Temp\ceraii\src\ceraii.c(193,16): warning C4013: 'on_exit' undefined; assuming extern returning int
1>D:\Code\Temp\ceraii\src\ceraii.c(196,18): warning C4388: '>=': signed/unsigned mismatch
```

**Comment by septag** [comment]
well, I guess it's already shown in the _appveyor_, sorry for redundant post!
